### ISSUE TITLE
No MQTT Support

### ISSUE THREAD

**Issue by ypogeios** [sshoecraft/jbdtool#11]
Hello,
i installed the phao.mqtt.c library.
After that i compiled the jbdtool and i get values from the BMS over serial.
When i try to put -m for mqtt i get a response: 
jbdtool: invalid option -- 'm'
jbdtool version 1.8 build 202209041911
usage: jbdtool [-abcjJFrwlhXN] [-f filename] [-t <module:target>] [-o output file]
arguments:
  -d <#>                debug output
  -c            comma-delimited output
  -g <on|off>   charging on/off
  -G <on|off>   discharging on/off
  -j            JSON output
  -J            JSON output pretty print
  -F            Flatten JSON arrays
  -r            read parameters
  -a            read all parameters
  -w            write parameters
  -l            list supported parameters
  -h            this output
  -f <filename> input filename for read/write.
  -o <filename> output filename
  -t <transport:target> transport & target
  -e <opts>     transport-specific opts
  -n            numbers only; dont interpret
  -X            reset BMS
  -N            dont wait if locked

What am i missing?

**Comment by sshoecraft** [comment]
did you enable MQTT in the makefile before building jbdtool?

make clean
then edit makefile ... set MQTT=yes
make

**Comment by ypogeios** [comment]
Thank you very much,
forgot to make clean.
BR,
ypogeios
