### ISSUE TITLE
Set "Balance current"

### ISSUE THREAD

**Issue by eliafino** [sshoecraft/jbdtool#12]
Hi, thanks for your work!

There is a way to set "Balance current"? I writed correctly "Difference opening voltage value" (BalanceWindow) to 5mV, but I can't find where to set the current, default "180mA" to max "260mA"

**Comment by sshoecraft** [comment]
No way to set the current that I know of - newer ones may be able to, but I don't have access to them.  You might contact JBD (try messaging on alibaba) and see if they have a new API for the new boards.
