### ISSUE TITLE
Very slow reading

### ISSUE THREAD

**Issue by eliafino** [sshoecraft/jbdtool#13]
Unfortunately I get a response about every 7 seconds. Is there any way to speed up the query? Now my BMS is connected with BT, serial connection is more fast?

Thanks!

**Comment by sshoecraft** [comment]
That seems very slow even with BT.  I finally got a JBD BT adapter so will test speeds.

I use a wifi adapter on mine (I have 14 BMS) and its very fast (< 2 seconds to read).  The wifi adapter uses the serial/uart interface.

https://diysolarforum.com/threads/jbd-bms-wi-fi-module.17252/

**Comment by eliafino** [comment]
Thanks, now is connected with serial, 1 second, super fast!
