### ISSUE TITLE
seeking for MQTT Client - compile failure

### ISSUE THREAD

**Issue by VictorBucha** [sshoecraft/jbdtool#2]
Greetings,

Despite having mosquitto  latest version on my RPi4, I can't compile:

gcc -MT main.o -MMD -MP -MF .deps/main.d -Wall -g -DDEBUG=1 -DMQTT -DBLUETOOTH   -c -o main.o main.c
In file included from main.c:31:
mqtt.h:6:10: fatal error: MQTTClient.h: No such file or directory
 #include <MQTTClient.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [/home/pi/jbdtool/Makefile:82: main.o] Error 1

root@raspberrypi:/home/pi/jbdtool# apt install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
mosquitto is already the newest version (1.5.7-1+deb10u1).

**Comment by foxriver76** [comment]
I also had to install Paho MQTT additionally to just installing mosquitto - https://www.eclipse.org/paho/index.php?page=clients/c/index.php

**Comment by sshoecraft** [comment]
thank you for that reminder ... I changed the README to state it requires the paho.mqtt.c library vs mosquitto.
