### ISSUE TITLE
MQTT user and password are not applied 

### ISSUE THREAD

**Issue by foxriver76** [sshoecraft/jbdtool#4]
When providing mqtt user and password it is not transmitted to the Server making auth not possible.

**Comment by foxriver76** [comment]
I am not much into C but maybe it’s because of https://github.com/sshoecraft/jbdtool/blob/d113835a5675c9aa2148743758fce8243f39dedf/mqtt.c#L72

**Comment by dalklein** [comment]
I think it's working for me, at least the mqtt messages are going through, and I think I have mosquitto set up requiring user & pwd.  As follows:

printf "\n%s\n"  "Starting JBD BMS mqtt reader instances, multiple in background"
jbdtool -t ip:192.168.15.34,23 -m 192.168.15.15:BMS_ETR:JBD_ET_rear:mqtt_user:mqtt_user_pw -i 180 &
sleep 2
jbdtool -t ip:192.168.15.35,23 -m 192.168.15.15:BMS_ETF:JBD_ET_front:mqtt_user:mqtt_user_pw -i 181 &

**Comment by foxriver76** [comment]
I‘ve used the same formatting and no credentials were transmitted to my mqtt broker, where the credentials are logged if incorrect, user as well as password were undefined. W/o credentials everything works fine. 

Currently not that important but would be nice if it works.

**Comment by sshoecraft** [comment]
This may be due to the MQTT library it's linking against.   I'll try to look at this tonight, but in the meantime if you want test, just change "paho-mqtt3c" to "paho-mqtt3cs" in the Makefile.  Note it may require other SSL libs to link with.

**Comment by sshoecraft** [comment]
I updated the source and tested.  Please refresh your local copy, compile & test.

**Comment by foxriver76** [comment]
Connection to the server now works with auth, but no data is sent to the broker anymore

**Comment by sshoecraft** [comment]
I apologize I simply did not get notified that you responded

I'll test against mosquitto with user and pass enabled on the mosq server

**Comment by sshoecraft** [comment]
Hi did this ever get resolved?  I just tested using a username/password on my mosquitto server and it worked.

**Comment by sshoecraft** [comment]
Can you check out the latest version and verify if this issue was resolved or not?
